baseURL = "https://yodogawa-diary.vercel.app/"
languageCode = "ja"
title = "河川敷日記"
defaultContentLanguage = "ja"
[pagination]
  pagerSize = 3

[params]
  tagline = "不定期・書き散らし・カレーうどん"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
